### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by Harlber** [alibaba/android_viewtracker#1]
`Features`中的 Two platform support (iOS & Android).
`platform` 应该为 `platforms `

**Comment by oldratlee** [comment]
@Harlber 方便给个PullRequest吗？

这样大家可以在仓库的Commit中看到你的贡献 ✨

**Comment by deanhust** [comment]
非常感谢@Harber提issues，已修复，也可以提供commit，欢迎一起共建
